# Generated by Django 4.2.5 on 2023-10-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_alter_flights_flight_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Departure_time',
            field=models.DateTimeField(),
        ),
    ]
