# Generated by Django 4.2.3 on 2023-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0003_alter_flights_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='booking_id',
            field=models.CharField(default=1007, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flights',
            name='Arrival_time',
            field=models.DateTimeField(verbose_name='Return'),
        ),
    ]
